# ************************************************************************
# Product    : Home information and control
# Date       : 2017-01-17
# Copyright  : Copyright (C) 2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : mqtt-broker/Dockerfile-rpi
# Version    : 1.0.0
# Author     : Bjorn Kjeholt
# *************************************************************************

FROM hypriot/rpi-alpine-scratch

RUN apk update && \
    apk upgrade && \
    apk add bash && \
    apk add vim && \
    apk add mosquitto && \
    rm -rf /var/cache/apk/*

RUN adduser --system --disabled-password --disabled-login mosquitto
USER mosquitto
EXPOSE 1883
CMD ["/usr/local/sbin/mosquitto"]
